ARG BASE_IMAGE=nginx:alpine3.20
FROM $BASE_IMAGE

ARG WEB_DIR
ARG CONF_PATH

RUN rm -rf /usr/share/nginx/html/*
COPY $CONF_PATH /etc/nginx/conf.d/default.conf
COPY $WEB_DIR /usr/share/nginx/html/

EXPOSE 8080