ARG BASE_IMAGE
ARG BUILD_DIR
FROM $BASE_IMAGE

RUN rm -rf /usr/share/nginx/html/*
COPY $BUILD_DIR/webserver-nginx.conf /etc/nginx/conf.d/default.conf
COPY $BUILD_DIR/yuzer/browser /usr/share/nginx/html/

# Set base-ref to ./ui/
RUN sed -i 's|<base href="./">|<base href="/ui/">|g' /usr/share/nginx/html/index.html

EXPOSE 8080