ARG BASE_IMAGE=node:22-alpine
FROM $BASE_IMAGE

ARG WEB_DIR

RUN rm -rf /app/dist
COPY $WEB_DIR /app/dist/

EXPOSE 8080

WORKDIR /app/dist/

# Default command
CMD echo "Current directory:" && \
    pwd && \
    echo "Run prisma deploy and status" && \
    npx prisma migrate deploy && \
    npx prisma migrate status && \
    echo "Starting node:" && \
    node app.js
