ARG BASE_IMAGE=node:22-alpine
FROM $BASE_IMAGE

ARG WEB_DIR

RUN rm -rf /app/dist
COPY $WEB_DIR /app/dist/

EXPOSE 8080

WORKDIR /app/dist/

# Default command
CMD echo "Current directory:" && \
    pwd && \
    echo "Content" && \
    ls && \
    echo "Prepare and install prisma" && \
    npx prisma generate && \
    npx prisma migrate deploy && \
    npx prisma migrate status && \
    echo "Starting node:" && \
    node app.js
